name: dtorrent_task
description: BitTorrent download client package written by pure Dart language.
version: 0.3.5
repository: https://github.com/moham96/dtorrent_task
issue_tracker: https://github.com/moham96/dtorrent_task/issues

environment:
  sdk: ">=2.15.0 <4.0.0"

dependencies:
  dtorrent_parser: ^1.0.8
  dtorrent_tracker: ^1.3.17
  bittorrent_dht: ^0.0.10
  dtorrent_common: ^1.0.5
  b_encode_decode: ^1.0.4
  utp_protocol: ^1.0.3
  dart_ipify: ^1.1.1
  events_emitter2: ^1.0.3
  mime: ^1.0.4
  collection: ^1.0.0
  crypto: ^3.0.3

dev_dependencies:
  lints: ^2.0.1
  path: ^1.8.3
  test: ^1.24.3
